services:
  - type: web
    plan: free
    name: QuizApp
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn QuizApp.asgi:application -k uvicorn.workers.UvicornWorker"
#    startCommand: "uvicorn QuizApp.asgi:application"
